encryption = "gpg"
[merge]
    command = "nvim"
    args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]
[diff]
    exclude = ["scripts"]
[status]
    exclude = ["scripts"]
[gpg]
    symmetric = true
